version: "3.8"

services:
  jekyll:
    image: ruby:3.1-bullseye
    container_name: jekyll-docs
    working_dir: /site
    environment:
      BUNDLE_PATH: /usr/local/bundle
      JEKYLL_ENV: development
      # .git を見せない場合はどちらかでリポジトリ名を明示
      # PAGES_REPO_NWO: owner/repo
    ports:
      - "8080:4000"     # まずはプレーンに公開（127.0.0.1: を付けない）
      - "35729:35729"
    volumes:
      - ./docs:/site
      - ./.git:/site/.git:ro   # .git を見せるなら PAGES_REPO_NWO は不要
      - bundle:/usr/local/bundle
    command: >
      bash -lc "
        gem install bundler &&
        bundle install &&
        bundle exec jekyll serve
          --config _config.yml,_config.docker.yml
          --source .
          --host 0.0.0.0 --port 4000
          --livereload --livereload-port 35729
          --trace --verbose
      "

volumes:
  bundle:
