# docker-compose.yml
services:
  jekyll:
    build:
      context: .
      args:
        PAGES_VERSION: "232"   # 必要に応じて更新
    image: github-pages-test-jekyll:1.0
    working_dir: /site
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ./docs:/site/docs
      - ./.git:/site/.git:ro
    environment:
      JEKYLL_ENV: production   # 本番に近い挙動で確認
      PAGES_REPO_NWO: "tettekete/github-pages-test"
    # 通常は CMD に従って serve が起動
    # build したいときだけ:
    # command: ["build","--source","docs"]
    command: [
      "serve",
      "--host","0.0.0.0",
      "--port","4000",
      "--safe",
      "--livereload",
      "--watch",
      "--force_polling",
      "--source","docs",
      "--config","docs/_config.yml,docs/_config.local.yml"
    ]
